let smartMobilePhones = [
  {
    id: "1s",
    name: "iQOO Z6 Lite 5G",
    descp: "Stellar Green, 6GB, 128GB, World's First Snapdragon 4.",
    price: "12000",
    img: "images/mobile/iqooz6.jpg",
  },
  {
    id: "2s",
    name: "Redmi 12 5G",
    descp: "Jade Black, 4GB 128GB, India's 1st Snapdragon4.",
    price: "11999",
    img: "images/mobile/redmi.jpg",
  },
  {
    id: "3s",
    name: "OnePlus Nord CE 2",
    descp: "8GB,256GB, Snapdragon695 5G Processor.",
    price: "17999",
    img: "images/mobile/one_plus.jpg",
  },
  {
    id: "4s",
    name: "Honor 90",
    descp: "Emerald Green, 12GB + 512GB",
    price: "33000",
    img: "images/mobile/honor.jpg",
  },
  {
    id: "5s",
    name: "Samsung Galaxy M34 5G",
    descp: "Waterfall Blue,6GB,128GB",
    price: "16900",
    img: "images/mobile/samsung.jpg",
  },
  {
    id: "6s",
    name: "realme narzo N53",
    descp: "Feather Gold, 4GB+64GB Fastest Charging",
    price: "7000",
    img: "images/mobile/realme.jpg",
  },
  {
    id: "7s",
    name: "realme narzo 60X 5G",
    descp: "Nebula Purple 4GB, 128GB Storage",
    price: "11000",
    img: "images/mobile/realme_narzo.jpg",
  },
  {
    id: "8s",
    name: "TECNO POP 7 Pro ",
    descp: "Uyuni Blue, 3GB RAM,64GB Storage",
    price: "6299",
    img: "images/mobile/tecno.jpg",
  },
  {
    id: "9s",
    name: "Lava Blaze 5G",
    descp: "Glass Green, 6GB RAM, UFS 2.2 128GB Storage",
    price: "10999",
    img: "images/mobile/lava.jpg",
  },
  {
    id: "10s",
    name: "Vivo Y16",
    descp: "Stellar Black, 4GB RAM, 128GB Storage",
    price: "11999",
    img: "images/mobile/vivo.jpg",
  },
];
